#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename	"PROJECTNAME.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"PROJECTNAME VST3 (64Bit)"
#else
#define stringFileDescription	"PROJECTNAME VST3"
#endif
#define stringCompanyName		"CORPNAME"
#define stringLegalCopyright	"COPYRIGHTNOTICE"
#define stringLegalTrademarks	"TRADEMARKNOTICE"